common-pg/src/main/scala/com/socrata/pg/Version.scala
project/Dependencies.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala

After review, I'd like to bump dependencies to non snapshot.

Upgrade to socrata-http 3.x

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerTest.scala
project/Dependencies.scala
soql-server-pg/src/test/resources/fixtures/select-magnitude.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLMathFunctionsTest.scala

Pair CR: @chitang
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/soql-postgres-adapter/43)

add soql function magnitude

---

project/Dependencies.scala
project/SoqlServerPG.scala
soql-server-pg/src/main/resources/reference.conf
soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/config/QueryServerConfig.scala

so it doesn't fall over on high load

Upgrade to socrata-http 3.3.0, use bounded queues

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
soql-server-pg/src/test/resources/fixtures/where-money-eq-txt.json
soql-server-pg/src/test/resources/fixtures/where-money-ge-txt.json
soql-server-pg/src/test/resources/fixtures/where-money-gt-txt.json
soql-server-pg/src/test/resources/fixtures/where-money-le-txt.json
soql-server-pg/src/test/resources/fixtures/where-money-lt-txt.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLMoneyFunctionsTest.scala

Text->Money conversion to support queries like 'select * where price > '1.50'

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerTest.scala
soql-server-pg/src/test/resources/fixtures/group-case.json
soql-server-pg/src/test/resources/fixtures/where-case-or.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLCaseFunctionTest.scala

It is here.  Why not include another function?

case function

---

common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala

Only add ST_AsBinary in outermost soql.
Quote identifiers more aggressively.

These are problematic when we start using chained soql.

---

project/Dependencies.scala
store-pg/docker/Dockerfile
version.sbt

Updates to version 2.1.5 of data-coordinator

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctionsGeometry.scala
project/Dependencies.scala
soql-server-pg/src/test/resources/fixtures/select-point-lat-lng.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLGeomFunctionsTest.scala

Won't build until we bump soql-reference.

Add SoQL functions point.latitude, point.longitude

---

project/Dependencies.scala
store-pg/docker/Dockerfile

Fixed version of secondary watcher

EN-4034: Update secondary watcher docker image

---

version.sbt

Reverts socrata-platform/soql-postgres-adapter#140

Revert "En 4323/hotfix"

---

project/Dependencies.scala
store-pg/docker/Dockerfile

Pickup more changes to secondary-watcher

---

store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala

Start curator

---

store-pg/docker/secondary.conf.j2

Fix bug with config; must add ints to ints

---

store-pg/docker/secondary.conf.j2

Take three at jinja2 syntax

---

store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala

..leading to slow updates on large datasets
This isn't in `optimize` because that pretty much assumes it's creating
userspace indexes.

System PK index wasn't getting created in all circumstances

---

common-pg/src/main/scala/com/socrata/pg/store/SoQLCommon.scala
project/Dependencies.scala

Implement soqlAnalyzer to still compile.

Use data-coordinator library version 3.1.5

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
project/Dependencies.scala
soql-server-pg/src/test/resources/fixtures/group-floatingtimestamp-extract-dow.json
soql-server-pg/src/test/resources/fixtures/group-floatingtimestamp-extract-hh.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLTruncateFunctionsTest.scala

These functions provide support for the apps team.

EN-14870 Add date_extract_xxx(floating_timestamp) functions.

---

soql-server-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala

As per https://www.postgresql.org/docs/9.6/static/when-can-parallel-query-be-used.html parallel
query can not be used if:
The client sends an Execute message with a non-zero fetch count.
See the discussion of the extended query protocol. Since libpq
currently provides no way to send such a message, this can only
occur when using a client that does not rely on libpq. If this is
a frequent occurrence, it may be a good idea to set
max_parallel_workers_per_gather in sessions where it is likely, so
as to avoid generating query plans that may be suboptimal when run
serially.
We set a fetch size so we can stream resuls without the jdbc driver
buffering them all.  This results in the driver using a cursor which
prevents parallel query action.
However, given that most of the queries that really …

EN-16779: Enable parallel queries by setting fetchSize to 0

---

soql-server-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala

I saw one case where our frontend code is fetching 1001 rows, so
bump the fetch size a trivial amount so we aren't just missing out
on being able to set it to 0 and use parallel queries.

Bump up fetch size from 1000 to 1025 to cover a few edge cases.

---

project/Dependencies.scala

This brings in this fix for a tight spin loop in the secondary watcher:
https://github.com/socrata-platform/data-coordinator/commit/5a8cb1bc49d02248766ca7353df1f500b56edfa2

Bump dc version.

---

configs/soql-postgres-adapter.conf

Needs to include value for collocation.group

SPARTA: Fix secondary-watcher-pg config

---

.solo/soql-server-pg.json

It doesn't appear to listen on 6091?

ENG: Correct soql-server solo port.

---

.gitignore
.solo/secondary-watcher-pg-alpha.json
.solo/secondary-watcher-pg-bravo.json
.solo/secondary-watcher-pg-charlie.json
bin/start_secondary_watcher_pg.sh
bin/start_secondary_watcher_pg_alpha.sh
bin/start_secondary_watcher_pg_bravo.sh
bin/start_secondary_watcher_pg_charlie.sh
bin/start_secondary_watcher_pg_docker_alpha.sh
bin/start_secondary_watcher_pg_docker_bravo.sh
bin/start_secondary_watcher_pg_docker_charlie.sh
configs/application-alpha.conf
configs/application-bravo.conf
configs/application-charlie.conf
store-pg/docker/Dockerfile

Start scripts for solo for running secondary-watcher-pgs
for the phonetic truth cluster "alpha", "bravo", "charlie"

SPARTA: Starts scripts for solo for phonetic SWs

---

store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala

EN-27852 Handle new computation strategy events

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
project/Dependencies.scala
soql-server-pg/src/test/resources/fixtures/make_one.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLWindowFunctionsTest.scala

1. Support order by
2. Add row_number, rank, dense_rank

EN-31669 Window function support, phase 2

---

common-pg/src/main/resources/com/socrata/pg/store/schema/20191224-add-some-dc-tables.xml
common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml

But which some DC stuff it calls expects to exist

Add some tables to the secondary database that it will not use

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerLocationTest.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerUrlTest.scala

This interact better with numeric type.

EN-38765 Make count return type numeric (previously bigint)

---

project/Dependencies.scala

Not actually EN-37516, but necessary to fix it.

Bump data-coordinator dependency

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerLocationTest.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerUrlTest.scala
project/Dependencies.scala

Count distinct still does not work with window function.  It is not supported in Postgres (at least in v11) anyway.

EN-42634: count expression/* + window function (#164)

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
project/Dependencies.scala

Need to fix up soql reference when that is merged

Add iif function

---

common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
common-pg/src/main/scala/com/socrata/pg/soql/package.scala
common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
common-pg/src/main/scala/com/socrata/soql/analyzer/SoQLAnalyzerHelper.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerTest.scala
project/Dependencies.scala
soql-server-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala
soql-server-pg/src/main/scala/com/socrata/pg/query/RowReaderQuerier.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
soql-server-pg/src/test/resources/fixtures/mutate-create-bird-dataset.json
soql-server-pg/src/test/resources/fixtures/mutate-create-cat-dataset.json
soql-server-pg/src/test/resources/fixtures/mutate-create-dog-dataset.json
soql-server-pg/src/test/resources/fixtures/mutate-create-fish-dataset.json
soql-server-pg/src/test/resources/fixtures/union-mixed-and-nested.json
soql-server-pg/src/test/resources/fixtures/union-no-table-alias.json
soql-server-pg/src/test/resources/fixtures/union-table-alias.json
soql-server-pg/src/test/resources/fixtures/union-urls.json
soql-server-pg/src/test/scala/com/socrata/pg/server/PGQueryServerDatabaseTestBase.scala
soql-server-pg/src/test/scala/com/socrata/pg/server/QueryTest.scala
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLUnionTest.scala

I have not published soql reference yet.  It can't build.  But i want a quick glance before we do.

Union - BinaryTree

---

common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
project/Dependencies.scala

This reverts commit f3721cf3663b6b73a6fd4667a39cfd528db76bd9.

Revert "Revert "Lateral joins (#385)""

---

common-pg/src/main/scala/com/socrata/pg/config/StoreConfig.scala
store-pg/docker/Dockerfile
store-pg/docker/secondary.conf.j2
store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
store-pg/src/main/scala/com/socrata/pg/store/events/RowsChangedPreviewConfig.scala
store-pg/src/main/scala/com/socrata/pg/store/events/RowsChangedPreviewHandler.scala

Also configure it in a less-silly way.

Make the decision about whether to copy on upsert more flexible

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
project/Dependencies.scala

Added functions for:
`regr_slope`
`regr_intercept`
`regr_r2`
`ln`

add regr_slope/r2/intercept and natural log functions

---

common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala

Cannot find columns from parent joins within lateral joins

EN-46482: Lateral joins cannot access fields from joins in parent scope

---

common-pg/src/main/scala/com/socrata/pg/store/SecondarySchemaLoader.scala

In particular, only do it if its definition has actually changed.

Be less eager to recreate the full text search index for datasets

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctionsGeometry.scala
project/Dependencies.scala

Adding:
area => ST_Area - return the area of a geometry
polygon_intersection => ST_Intersection - return the geometry of a an intersecting area (or null if they don't intersect)
ntile(N) => NTILE - integer ranging from 1 to the argument value, dividing the partition as equally as possible. Useful for getting quantiles through SoQL.
Bump version

add wrapper for ST_Area, ST_Intersection, and NTILE(N) functionality

---

common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctionsLocation.scala
common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
project/Dependencies.scala
soql-server-pg/src/test/resources/fixtures/avg_over_columns_nulls.json
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLGroupTest.scala
soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLWindowFunctionsTest.scala

curl -v "http://localhost:6010/resource/_catx-xxxx?%24query=select+count(*)+filter(where+false)+over()"

EN-49288: Aggregate function call filter

---

common-pg/src/main/resources/com/socrata/pg/store/schema/20220208-add-data-shape-version.xml
common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
project/Dependencies.scala
store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
store-pg/src/main/scala/com/socrata/pg/store/events/WorkingCopyCreatedHandler.scala
store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryTestBase.scala
store-pg/src/test/scala/com/socrata/pg/store/ResyncTest.scala
store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
store-pg/src/test/scala/com/socrata/pg/store/events/WorkingCopyCreatedHandlerTest.scala

This doesn't actually care about it, but because it uses DC's database
code it needs to fake caring.

Add data shape version

---

common-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala
common-pg/src/main/scala/com/socrata/pg/query/ExplainInfo.scala
common-pg/src/main/scala/com/socrata/pg/query/QueryResult.scala
common-pg/src/main/scala/com/socrata/pg/query/QueryServerHelper.scala
common-pg/src/main/scala/com/socrata/pg/query/RowReaderQuerier.scala
common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
soql-server-pg/src/test/scala/com/socrata/pg/server/PGQueryServerDatabaseTestBase.scala
soql-server-pg/src/test/scala/com/socrata/pg/server/QueryTest.scala
store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala

Move functions from soql—server-pg to common-pg so that they can be shared between rollup and query.

EN-51742: Add join support in rollup

---

common-pg/src/main/scala/com/socrata/pg/store/LocalRollupInfo.scala
common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryDatasetMapWriter.scala
project/Dependencies.scala
store-pg/src/main/scala/com/socrata/pg/store/events/RollupCreatedOrUpdatedHandler.scala
store-pg/src/test/scala/com/socrata/pg/store/DatabaseTestBase.scala
store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
version.sbt

Just adapting to truth db.  Not adding this column in secondaries (at least yet)

EN-52670: Add column rollup_map.raw_soql

---

common-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala
common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala

So do the underscore thing with them

PG14 wants setting name-components to be valid identifiers

---

project/Dependencies.scala

For the new SKIP LOCKED implementation of finding
new work in the secondary-watcher

Update data-coordinator dependency

---

soql-server-pg/docker/Dockerfile
store-pg/docker/Dockerfile

EN-59475
Upgrade both docker base images, soql-server-pg and secondary-watcher-pg

EN-59474: upgrade docker base image

---

Jenkinsfile

In the Jenkinsfile, on release cuts, the dockerized image is deployed to RC.
In the Jenkinsfile, on release builds, the dockerized image is not deployed to RC.
Also:
- new parameter RELEASE_DRY_RUN added to ease testing
- changed stage name from "Cut" to "Release Tag"
- used simpler syntax for deploying
- simplified logic for which stage to build

EN-59946: update Jenkinsfile

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/FuncallSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala

* left_pad
* right_pad
* epoch_seconds
* date_diff_d
* some simple geometry functions
Also make the expression tests trim out all the common non-expression parts of the generated sql.

Add some functions

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/FuncallSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala

* to_floating_timestamp
* json properties, indexing, and casts between it and json
* casts to/from text and boolean or number
* Location subcolumn extraction and the generic location constructor

More functions

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
project/Dependencies.scala

related to https://github.com/socrata-platform/soql-reference/pull/319

width_bucket soql function

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/FuncallSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala

* round
* all aggregate functions can also be used as window functions

Yet more functions

---

common-pg/src/main/resources/com/socrata/pg/store/schema/20230626-nontrivial-soql-functions.xml
common-pg/src/main/resources/com/socrata/pg/store/schema/20230626-soql-compress-compound.xml
common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
common-pg/src/main/scala/com/socrata/pg/analyzer2/ExprSql.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/FuncallSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/Geo.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/Rep.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRep.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/Sqlizer.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/SqlizerTest.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/TestRepProvider.scala

Pretty much all of this code is very uninteresting, and as SQL it's easier to read than as Doc-building code.

Offload a bunch of stuff into stored procedures

---

Jenkinsfile

After building docker images, they are pushed to all registries.
After building docker images:
- if the image is for staging, it is pushed only to the internal registry
- if the image is for release, it is pushed to all registries

EN-60862: for staging push to internal registry only

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRep.scala
project/Dependencies.scala

Also bump the postgresql jdbc driver to the latest so that PGInterval has all the methods I want to call on it.

Implement interval rep

---

common-pg/src/main/resources/com/socrata/pg/store/schema/20231020-soql-make-point.xml
common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerPostgres.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerRedshift.scala
common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctionsGeometry.scala
project/Dependencies.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala

Plus ScopedResourceName moved in soql-reference

Add make_point

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerRedshift.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTestRedshift.scala

some window functions have limitations in redshift:
https://socrata.atlassian.net/wiki/spaces/PD/pages/2717450537/Functionalities+in+Redshift+with+limitations
some window functions are not supported in redshift:
https://socrata.atlassian.net/wiki/spaces/PD/pages/2706243589/Complex+functions+not+implemented+in+Redshift

[EN-63001] - Dalia/windowed functions

---

common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctionsGeometry.scala

Did this already on the new one but I missed the old one.

Fix the other half of the make_point function for older postgis

---

README.md

This just adds a little high-level verbiage to the README some newcomers to the repo can at a glance glean why it exists.

NOJIRA: Add a high-level description of what the repo contains

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/Namespaces.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLExprSqlFactory.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRep.scala
common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLSqlizer.scala
common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala

Just removing the explicit "Postgres" from things that had had it added.

A little post-redshift-extraction cleanup

---

common-pg/src/main/scala/com/socrata/pg/store/RollupAnalyzer.scala
project/Dependencies.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ETagify.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Hashable.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala

Also use them when computing the etag

Pass column hints from the input analysis to the output cjson

---

common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRep.scala
common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
common-pg/src/test/scala/com/socrata/pg/analyzer2/TestRepProvider.scala
project/Dependencies.scala

It's not actually _used_ anywhere really (except the indices) but just keeping up with things.
I'll need to do a refactor of this sometime.  It's a little repetitive.

Update soql-reference for the new ingress stuff

---

Jenkinsfile

This commit will test https://github.com/socrata/pipelines/pull/142, which creates vars for Release Metatdata Service integration and then it will add the integration to write to RMS for release builds.

EN-62919: write build to rms

---

common-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala

With UNIONs etc, "look at the rightmost analysis's limit" is wrong. Instead, compute an "effective limit" which will be an upper bound based on the actual operator node, and use that.

Better LIMIT heuristic for row streaming

---

soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Deserializer.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala

Also return the sf resource names of tables in the "dataVersions" field instead of the internal names.

Produce the data-out-of-date header

---

project/Dependencies.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Deserializer.scala
soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Hashable.scala

Also remove a couple of unused parameters from AuxTableData.deserialize

Bump soql-reference

---

common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryUniverse.scala
store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala

Just dump them into a single COPY command's stream

Don't chunk rows when resyncing

---

soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala

Not if it is found but the table isn't out of date

Complain about aux data not being found if it really isn't found

---

common-pg/build.sbt
common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryUniverse.scala
project/Dependencies.scala

* we now need to depend on the http server explicitly
* Remove an unused method from PGSecondaryUniverse

Bump coordinatorlib

---

soql-server-pg/docker/soql-server-pg.conf.j2

So construct it ourselves in jinja

ECS isn't going to want to give us the entire redis url fully-formed

---

service-registry/mkdocs.yaml
service-registry/secondary-watcher-pg-service-registry.yaml
service-registry/service-registry.yaml
service-registry/soql-server-pg-service-registry.yaml

this is for the backstage implementation
https://github.com/socrata/service-registry

EN-76014 add service registry config
