- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerTest.scala
If not specified, postgres uses its default as set in default_text_search_config.  In RDS this is
set to simple whereas in other environments it gets set to english based on the locale.
http://www.postgresql.org/docs/9.4/static/runtime-config-client.html#GUC-DEFAULT-TEXT-SEARCH-CONFIG
The result was, for example, 'vancouver' getting indexed as 'vancouv' but the same wasn't happening
at query time so no results were found.
> Specify english when querying since we specify it creating the index.

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- common-pg/src/main/scala/com/socrata/pg/store/index/Indexable.scala
- common-pg/src/test/scala/com/socrata/pg/store/PGSecondaryUniverseTestBase.scala
- project/Dependencies.scala
- soql-server-pg/src/test/resources/fixtures/group-case.json
- soql-server-pg/src/test/resources/fixtures/group-floatingtimestamp-trunc-y.json
- soql-server-pg/src/test/resources/fixtures/group-text-expr.json
- soql-server-pg/src/test/resources/fixtures/group-text-order-count.json
- soql-server-pg/src/test/resources/fixtures/group-text.json
- soql-server-pg/src/test/resources/fixtures/mutate-create.json
- soql-server-pg/src/test/resources/fixtures/result.json
- soql-server-pg/src/test/resources/fixtures/select-signed_magnitude_10.json
- soql-server-pg/src/test/resources/fixtures/select-signed_magnitude_linear.json
- soql-server-pg/src/test/resources/fixtures/where-conv-txt2blob.json
- soql-server-pg/src/test/resources/fixtures/where-null-isnull.json
- soql-server-pg/src/test/resources/fixtures/where-str-ne.json
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLConversionFunctionsTest.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLGroupTest.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLLimitOffsetTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupDropTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
Blobs are represented by a text column, and there are only two functions
on them: comparing them for equality, and an identity-ish conversion of
text to blob (which is implicitly used on literal string to convert them
to blob values if required).
> Enable blob type

- soql-server-pg/src/test/scala/com/socrata/pg/server/PGQueryServerDatabaseTestBase.scala
By accepting a number if it's within 0.001% of the expected value
> Make the tests be more flexible about floating-point numbers

- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
Typically these are parsing errors if the schema has changed and the rollup hasn't been updated, eg.
delta importer drops and re-adds columns on schema changes and they get different internal ids.
This is a partial revert of 6c433194 which introduced this bug in a code review style change.  The issue
was it resulted in e not being typed as a Throwable, so it instead was calling an overloaded
warn(message : scala.Predef.String, params : scala.AnyRef*) method which then effectively ignored the
params argument.
> EN-2137: Properly log cause of being unable to populate a rollup.

- common-pg/src/main/resources/com/socrata/pg/store/schema/20160107-create-computation-strategy-map.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/20160111-add-field-name-columns.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryLogger.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerTest.scala
- common-pg/src/test/scala/com/socrata/pg/store/PGSecondaryUniverseTestBase.scala
- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- store-pg/docker/Dockerfile
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/ColumnCreatedHandler.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/FieldNameUpdatedHandler.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryTestBase.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryUniverseTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/ResyncTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/events/FieldNameUpdatedHandlerTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/events/SystemRowIdentifierChangedHandlerTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/events/VersionColumnChangedHandlerTest.scala
Bumps to v.2.0.0 of data-coordinator.
- BD migrations need to be run, but should otherwise be releasable
- Need to write tests
> EN-158: Updates to use new version of data-coordinator

- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
See https://socrata.atlassian.net/browse/EN-3281
We are currently triggering unnecessary resyncs on the version event immediately following the dropping of a working copy. This is because we are using `PostgresDatasetMapReader.latest` to determine the list of copies that have been replicated to the secondary, and this method excludes discarded working copies whose dropCopy event has in fact been synced to the secondary. This commit makes sure that we consider those discarded copies when deciding whether to resync.
> EN-3281 - Consider discarded copies when determining dataVersion delta between truth and PG secondary

- project/Dependencies.scala
- store-pg/docker/Dockerfile
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/test/scala/com/socrata/pg/store/ResyncTest.scala
Secondary.dropCopy(.) is part of the resync
path for discarded and snappshotted copies.
Keep an entry in `copy_map` for a discarded
copy during resync only if it is the latest
copy of the dataset.
We want to do this because secondary-watcher
updates the secondary manifest to say that
a secondary is done with the _latest_ copy
of a dataset after resync.
> EN-4323: Implement Secondary.dropCopy(.)

- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- common-pg/src/test/scala/com/socrata/pg/store/PGSecondaryUniverseTestBase.scala
It was succeeding only because a map is traversed at a specific order and return the "right" key columns from two conflicting columns.
This actually removes the duplicated key column.
> When I try to bump DC to v2.1.14-SNAPSHOT, a test suddenly fails.

- project/Dependencies.scala
- store-pg/docker/Dockerfile
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- version.sbt
Fix false assumptions around:
* most-recently-created copy is the most-recent copy
Pickup secondary-watcher changes
> EN-5261: Fix most-recent copy related bugs.

- soql-server-pg/docker/Dockerfile
Jenkins jobs are updated to build the code with Java 8. Build passed in Jenkins and container is running fine in staging under Java 8.
> EN-5915: Use Java8 base image for dockerizing soql-server-pg

- store-pg/src/main/scala/com/socrata/pg/store/events/RowsChangedPreviewHandler.scala
Otherwise they just hang around forever; new rollups will be
created for the new table.
> Drop old rollup tables when doing a table-replacing upsert

- store-pg/docker/Dockerfile
Looks good so far in Jenkins and staging. Will monitor in staging for a bit before merging.
> EN-5912: Use Java8 base image for secondary-watcher-pg

- project/BuildSettings.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/RowsChangedPreviewHandler.scala
..when a table-copy happens because of a large upsert.
The cause of the table copy and times for its creation and re-indexing
and re-rolling-up are logged.
> Add logging around various parts of the log playback

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- soql-server-pg/src/test/resources/fixtures/select-location-address-only.json
- soql-server-pg/src/test/resources/fixtures/select-location-lat-lng-only.json
- soql-server-pg/src/test/resources/fixtures/select-phone-number.json
- soql-server-pg/src/test/resources/fixtures/select-phone-type.json
- soql-server-pg/src/test/resources/fixtures/select-url-description.json
- soql-server-pg/src/test/resources/fixtures/select-url-url.json
This is done to make it easy to work with obe
select * where phone = '4251234567' will only compare phone.number
select * where phone = 'Home: 4251234567' will compare both
> EN-5371: Skip null sub column

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/store/index/FullTextSearch.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
When no columns are searchable, return false instead of not having a condition.
> Chained SoQL search needs to run in the context of the previous SoQL.

- common-pg/src/main/scala/com/socrata/pg/store/Migration.scala
- common-pg/src/main/scala/com/socrata/pg/store/NonCommittingJdbcConnection.scala
- store-pg/src/main/scala/com/socrata/pg/store/SchemaMigrator.scala
Run migration in one transaction.
> Acquiring locks timeouts in 30s for migration.

- common-pg/src/main/scala/com/socrata/pg/config/StoreConfig.scala
- project/Dependencies.scala
- project/StorePG.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/RowsChangedPreviewConfig.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/RowsChangedPreviewHandler.scala
Since we don't actually know what our thresholds should be for making an indexless copy on large upserts, this change allows us to store Clojure functions in Zookeeper and update them at runtime to configure the behavior based on number of columns.
> En 7531 - runtime-configurable thresholds for table-copying

- README.md
- bin/run_migrations.sh
- soql-server-pg/docker/ship.d/run
- store-pg/src/main/scala/com/socrata/pg/store/Main.scala
- store-pg/src/main/scala/com/socrata/pg/store/MigrateSchema.scala
The migrations used to (and still do) live here too; that is no longer
a main class, and the docs and scripts have been updated to Do The Right
Thing to run them.
> Have only one `main` in store-pg

- project/Dependencies.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/test/scala/com/socrata/pg/store/ResyncTest.scala
This is probably fallout from the desecondarification of snapshots.
> Warn about dropping nonexistant copies, rather than bailing

- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
This got accidentally removed when we bumped the less useful timing
reports down to debug level.
> EN-11848: Add back info level rollup timing logging.

- project/Dependencies.scala
Secondary-watcher now has:
- retry logic around releasing claims
- health check on updating claimed_at
- in-memory working set to only update
claimed_at time for datasets that
the secondary is actually still working on
> EN-4308: Use improved secondary-watcher version

- soql-server-pg/docker/soql-server-pg.conf.j2
Setting onAcquire doesn't actually do anything unless you have a connection customizer configured.
> EN-12544: Actually set work_mem for soql-server-pg.

- project/Dependencies.scala
- soql-server-pg/src/test/scala/com/socrata/pg/store/SchemaTest.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/test/scala/com/socrata/pg/store/CurrentCopyNumberTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/CurrentVersionTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryUtil.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/events/WorkingCopyCreatedHandlerTest.scala
This helps reduce lock problems in future db migrations.
> Reduce lock duration on some system tables during rows updates.

- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryDatasetMapWriter.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryUtil.scala
- store-pg/src/test/scala/com/socrata/pg/store/ResyncTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
Resync imposes lock conflict with reads which leads to backing up of connections.  That eventually takes down a pg query server.
> EN-13224 Disable SoQL reads during resync.

- README.md
Copying and pasting context here:
**Why?**
Because passing `soda2.conf` to this migration doesn't work. It throws this error: 
```bash
No configuration setting found for key 'com.socrata.pg'
```
**For context (from #hello-world slack channel)**
> Brian Tong: any advice on running the migration for soql-postgres-adapter? I’m getting a similar error from previous conversations in here about `No configuration setting found for key 'com.socrata.pg`', but I didn’t see any definitive solution in chat history
> Alexa Rüst: You might need both still?
You need a separate config file for the secondary-watcher-pg
So you probably want to use this https://github.com/socrata/docs/blob/master/onramp/services/pg-secondary.conf
corresponding update to install script here: …
> Update readme to correct *.conf file for running migration

- project/Dependencies.scala
Avoid deadlocks when updating multiple rows on the
`secondary_manifest` by first obtaining locks on
the rows in a deterministic order, i.e. ordery by
`dataset_system_id` then `store_id`.
> EN-12729: Avoid deadlocks with new SW lib version

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
This fixes soql like
SELECT ‘literal’ as x GROUP BY x
> EN-13048 Use group by position if we find literal

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
- project/Dependencies.scala
- soql-server-pg/src/test/resources/fixtures/distinct-group.json
- soql-server-pg/src/test/resources/fixtures/distinct.json
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLDistinctTest.scala
** DEPLOY soql-postgres-adapter BEFORE query-coordinator **
to avoid service interruption
Just the one in the select level.
SELECT DISTINCT col1, col2, …
not the one inside function
SELECT COUNT(DISTINCT col1)
> EN-14996 Add “Distinct” support

- store-pg/docker/secondary-watcher.conf.j2
Fix docker configuration so secondary-watcher
can send replication complete messages.
`com.socrata.zookeeper.ZooKeeperProvider` expects
a comma seperated string of hosts (not an array).
> EN-15144: Fix docker configuration

- store-pg/docker/secondary.conf.j2
Make it possible to optionally configure the
log level for com.socrata components to a higher
log level in docker for dugging Eurybates messages.
> EN-15144: Configurable com.socrata log level

- common-pg/src/main/scala/com/socrata/pg/error/RowSizeBufferSqlErrorHandler.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryTestBase.scala
- store-pg/src/test/scala/com/socrata/pg/store/events/RowDataUpdatedHandlerTest.scala
In commit 9b4871dbf8310bb5f9ccb7983b3a958afd6f729d, we previously added the functionality
to force a resync if a value is too large to index.  Going through resync, the value will be added,
the index creation will fail, and we will move on without an index on the column.
This wasn't working for updates because they are done as batch statements so you end up with a
BatchUpdateException.
Also, add some tests around these cases.  As part of that change the row update tests to use a published
dataset because unpublished datasets have fewer things (ie. indexes) on them.
> EN-14749: Fix "data too long to index" errors for row updates.

- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- common-pg/src/main/scala/com/socrata/soql/analyzer/SoQLAnalyzerHelper.scala
- project/Dependencies.scala
We want to do this now so that we will not be blocked if there is an urgent need to bump soil-ref for non join related work.
> EN-16084 Minimal change to bump soql-ref version.

- common-pg/src/main/resources/com/socrata/pg/store/schema/20170615-add-dataset-map-resource-name-index.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
- common-pg/src/main/scala/com/socrata/pg/store/Migration.scala
- project/Dependencies.scala
setChangeLogLockWaitTime to a value smaller (3s) than sql lock_timeout (30s) so that migrations where runInTransaction="false" should go through fine.
Also bump soql-refernce just to get the latest version which is a refactor w/o semantic change.
> EN-16800 Migration to create index on resource name (concurrently)

- project/Dependencies.scala
Secondary-watcher-pg can help move datasets between stores
to enable collocation. This does not have any locking and
must be manually triggered.
> EN-17014: SW PG can help move datasets

- configs/soql-postgres-adapter.conf
- project/Dependencies.scala
- store-pg/docker/Dockerfile
- store-pg/docker/secondary-watcher.conf.j2
Bring in new version of DC for updated SecondaryWatcher library
code that uses zookeeper lock to avoid race conditions when dropping
datasets from stores as part of collocation.
> EN-17014: Bring in new DC version for SW

- bin/start_soql_server_pg.sh
- configs/soql-postgres-adapter.conf
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
Changes to the reference.conf in new data-coordinator
version must of removed the value for:
`com.socrata.datacoordinator.common.curator.ensemble`
Also add stack trace for debugging config issues instead of using
the logger which is not configured and thus does not work.
> SPARTA: Fix start script for soql-server-pg

- store-pg/src/main/resources/secondary-manifest.json
Since we don't load PGSecondary dynamically insto SecondaryWatcher
any more we don't need this old file for that.
> SPARTA: Remove old file for dynamic class loading

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctionsLocation.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerLocationTest.scala
{"address": “101 Main St”, "city": “Seattle”, "state": "", "zip": “98104” }
We keep the key of null components.  SODA1 has the same behavior.  It is simpler.
> EN-23103 Allow human address to be partial null like

- common-pg/src/main/scala/com/socrata/pg/SecondaryBase.scala
The main use case is for the query server so you can more easily
trace back queries to requests.  This also work in the secondary
watcher code, although is probably less helpful there.
This relies on existing values that are set in the MDC for logging purposes.
Example secondary watcher value: "79 b0a971c5-d3c5-438f-b030-c313f7ee64e8 DatasetId(5)"
Example query server value: "90 4t4jvi0k5qs8qmdxrsygiwr4l _8qy9-my8i"
> Set the application name when getting a database connection.

- soql-server-pg/docker/ship.d/run
- store-pg/docker/ship.d/run
soql-server-pg _uses_ store-pg to run the migrations but store-pg isn't
included in the jar file anymore because it otherwise didn't use it.
So now do the migrations that the store jar is responsible for when the
store jar is deployed
> Move the database migrations into store-pg's start script

- soql-server-pg/src/main/scala/com/socrata/pg/query/DataSqlizerQuerier.scala
This gets logged many layers up the stack by the CountingHandler in socrata-http
however that is outside the ThreadRenamingHandler that gives context like request id
to the log line making it hard to find when there are many requests.
This will result in the exception being logged twice, once here and once by CountingHandler.
The correct fix for that would be to not bubble unhandled exceptions up to CountingHandler and
have a saner error handling framework within this code but that is a much bigger change to make
in a way that makes things cleaner and not just more convoluted.
> Log the SQL exception we get on failed SQL.

- common-pg/src/main/scala/com/socrata/pg/store/index/FullTextSearch.scala
* the to_tsvector search index created on secondaries has the columns ordered by their actual table column names
* however, the search query path works with column aliases, and used to order by those (missing the index)
* this updates the searchVector to attempt an ordering that will hit the index. It uses the underlying column id (ex: '6tcq_mbxm'), plus any subcolumn suffix to determine the order. This is not strictly the true column name (ex: u_6tcq_mbxm_28) but will work for ordering.
* if not all the CoreExpr in the searchVector are ColumnRefs, its not going to be possible for us to use any index anyway.
> EN-38580: when composing query for text search, attempt to use index

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLGroupTest.scala
QA: To repro:
1. create soql view - select field, ' ' as constant group by field, constant
2. $query=select field -> error
> EN-40387: Not selecting group by constant result in error

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
Cheetah regression:
querying a view with search
should honor search saved in a derived view with soql using soda v2.1 from nbe
> EN-24494: (leading) search sql generation bug around previous analysis

- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/WorkingCopyCreatedHandler.scala
- store-pg/src/test/scala/com/socrata/pg/store/DatabaseTestBase.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
The code assumed that data versions would increase by 1 each time; this
is no longer true.  Instead, fetch the previous data version from the
database.
Also remove the 0-row optimization, because it will break things (the
data version will still be changed, and therefore the table name)
> EN-42578: Plug rollup table leak

- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
If this resync was creating a new dataset from scratch (e.g., if there
was a collocation or the like to put a dataset in a secondary without
the log existing) it would create a rollup and then promptly schedule
it for dropping.
> Don't drop rollups that get created during resync

- common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
1. use rollup table name
2. use type rep if rep is not found
> EN-44281: Union/Query BinaryTree Rollup not used fix

- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
Part of preparation to support multiple rollups because of the introduction of unions
> Get rollup by either dataset internal name or resource name (for QC)

- common-pg/src/main/resources/com/socrata/pg/store/schema/20210420-create-onerow.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/20210420-create-single_row.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
- project/Dependencies.scala
* Create a columnless `onerow` table we can reference
* Only actually generate that reference if necessary
> Handle the single-row table special case

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
When converting a join into a from, keep track of the parameters
associated with that join more correctly (i.e., at all)
> Fix a bug in parameter bookkeeping in single_row elision

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- project/Dependencies.scala
Introduces:
`round(N, x)` function to round a number to the nearest x digits.
E.g.
round(3.1415, 3) => 3.142
round(315, -1) => 320
> EN-46401 - round SoQL function

- common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJsonbTest.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerLocationTest.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerUrlTest.scala
- project/Dependencies.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLUnionTest.scala
They can contain "-" now, so ensure we quote all aliases always, as the
_-prefix is no longer sufficient.
Most of this is just updating the tests to expect them.
> Update for new table aliases

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLUnionTest.scala
(SELECT A UNION SELECT B) INTERSECT SELECT C
Should behave correctly
> EN-47916: More aggressively generate parentheses in compound queries

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- project/Dependencies.scala
Before:
v3.8.1 soqlstdlib
After:
v3.11.2 soqlstdlib
Lead and Lag function bindings
> add lead/lag functions; bump soqlstdlib

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- common-pg/src/main/scala/com/socrata/pg/soql/SqlizeError.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/CJSONWriter.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QCRequestError.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
Select ‘invalid-period’::interval
Select ‘P1Y’::interval -- valid period but we do not support output
Select ‘t1rue’::boolean
Select ‘t1rue’:: number
> EN-49341: More improvement in error handling 400 (previously 500)

- common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
Previously going through cstring:
Filter: ((u_4n3z_8mii_6 >= ('2020-02-11T00:00:00.000'::cstring)::timestamp without time zone)
New:
Filter: (u_xh59_u4rh_18 = '2016-01-01 03:00:00'::timestamp without time zone)
> Streamline datetime literal parameters

- common-pg/src/main/resources/com/socrata/pg/store/schema/20220218-add-rollup-table-name.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
- common-pg/src/main/scala/com/socrata/pg/store/LocalRollupInfo.scala
- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryDatasetMapReader.scala
- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryDatasetMapWriter.scala
- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryUniverse.scala
- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/WorkingCopyCreatedHandler.scala
- store-pg/src/test/scala/com/socrata/pg/store/DatabaseTestBase.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryDatasetMapReaderTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryDatasetMapWriterTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/PGSecondaryTestBase.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupDropTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
- store-pg/src/test/scala/com/socrata/pg/store/events/WorkingCopyCreatedHandlerTest.scala
* Allow moving rollups between data versions
* Allow populating rollups on `optimize`
> Rollup improvements

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
- project/Dependencies.scala
Previously, these are failing:
SELECT
(
date_extract_y(floating_timestamp) || '-' || left_pad(date_extract_m(floating_timestamp) :: text, 2, '0') || '-' || left_pad(date_extract_d(floating_timestamp) :: text, 2, '0') 
)::floating_timestamp
SELECT (‘2020-‘ || ’02-02’)::floating_teimstamp
> EN-51220: Indirect literals should not generate timestamp parameters

- common-pg/src/main/scala/com/socrata/pg/query/QueryServerHelper.scala
- project/Dependencies.scala
- soql-server-pg/src/main/resources/reference.conf
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/config/QueryServerConfig.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/PGQueryServerDatabaseTestBase.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/QueryServerTest.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/QueryTest.scala
so that we get a consistent sql timeout error
http-query-timeout-delta = "2s"
> EN-49039: Limit $$query_timeout_seconds to 10 minutes unless it is debug

- store-pg/src/main/scala/com/socrata/pg/store/events/IndexDroppedHandler.scala
Because metadata was removed before actual drop which depends on the metadata.
> EN-52985: Delete did not drop the index

- store-pg/src/main/scala/com/socrata/pg/store/events/RowDataUpdatedHandler.scala
"81.97182190984103%" => "81.97%"
> Limit precision on row-update progress logs

- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLContextTest.scala
No need for it in that case, we can just look the value up in the map
ourselves and put it in the SQL as if it had been a string literal
itself.
If a non-string-literal is passed in, we'll still do the runtime lookup
but this should basically never happen.
> Don't compile `get_context(stringlit)` to a current_setting call

- common-pg/src/main/resources/com/socrata/pg/store/schema/20191224-add-some-dc-tables.xml
- project/Dependencies.scala
Occasionally we need to clean up orphans in secondaries.  We do not want this to race with SqlTableCleanup. (#369)
Put the special value '{}' in the cookie so that it will not be touched by SqlTableCleanup
Modified file
> Bump DC lib for

- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryDatasetMapWriter.scala
- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/SecondaryEventHandler.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupCopyDroppedHandlerTest.scala
Missed a few code paths:
* Upon copy drop, delete referenced rollups, not just rollups that reference us
* Method in RollupManager that is used in one place, missed dropping references
* Dropping unpublished working copies
> Fixes to rollups when dropping a copy

- common-pg/build.sbt
- common-pg/src/main/scala/com/socrata/pg/store/PGSecondaryDatasetMapReader.scala
- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- common-pg/src/main/scala/com/socrata/util/Timing.scala
- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
This change brings in a new library(rollup-metrics) and 
* logs the creation time and size of a rollup table that was built.
* logs when a rollup is hit
> EN-55757 rollup usage metrics

- common-pg/src/main/scala/com/socrata/pg/store/LocalRollupInfo.scala
Important characters in uniqueness should be in the front.
https://socrata.atlassian.net/browse/EN-57144
> EN-57144: Fix for postgres generating unique names

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SqlizeAnnotation.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/Sqlizer.scala
- project/Dependencies.scala
- soql-server-pg/build.sbt
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Deserializer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
The big change here is a rework of how processing the resultset works. It's now converted into an iterator of rows so that the inhibitRow option can just provide an empty iterator, so various bookeeping things that happened later before now happen earlier.
> Use the new debug info

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRep.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Deserializer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/Sqlizer.scala
Plumb the subcolumn info from upstream into the SoQLRepProvider so that SoQLLocation can select them into the normal compound column intermediate format.
The "specialness" of this is pretty nicely kept to a minimum - the subcolumn info needs to get passed into the soql rep provider, and we need to keep track of what table labels refer to what physical database tables, but other than that all the weirdness of fake-locations is managed entirely within SoQLLocation's Rep implementation.
> EN-60548: Fake-locations on the new query path

- common-pg/src/main/scala/com/socrata/pg/analyzer2/FuncallSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
* UTC-assuming truncation of `fixed_timestamp`
* subfield extractions for `floating_timestamp`
* timestamp +/-
* `human_address`
* `within_polygon` for both points and location
* the url type constructor
> Implement a bunch more functions

- common-pg/src/main/resources/com/socrata/pg/store/schema/20230619-add-discrete-median-function.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
* median
* median_disc
* regr_intercept
* regr_slope
median_disc is the most interesting one, because in order to support "median_disc(distinct whatever)" the custom aggregate function needed to be implemented for distinct mode.
> Median and linear regression aggregate functions

- common-pg/src/main/resources/com/socrata/pg/store/schema/20230620-citus-distribution-shim.xml
- common-pg/src/main/resources/com/socrata/pg/store/schema/migrate.xml
- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- common-pg/src/main/scala/com/socrata/pg/store/SecondarySchemaLoader.scala
- common-pg/src/main/scala/com/socrata/util/Citus.scala
This introduces a shim for letting Citus determine what column of a dataset to use for distribution.
The intention is for this to be temporary while we test Citus in a controlled environment.
The shim is implemented via a lookup table named `citus_dataset_distribution_map` and `citus_rollup_distribution_map`.
There are two places where a dataset table gets created currently:
- SecondarySchemaLoader#create
- com.socrata.pg.store.RollupManager#createRollupTable
> EN-60643: Citus distribution column shim

- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
This is also returned as the query's etag, but it's nice to have baked into the header record too.
> Return the query fingerprint in the cjson header

- common-pg/src/main/scala/com/socrata/pg/analyzer2/Rep.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SqlizerTest.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/TestRepProvider.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
* text literal sql is now more consistently `text 'foo'` rather than `'foo' :: text` or just `'foo'`
* Some places where we were using mkStringLiteral are now mkTextLiteral
* Debug info (most importantly "explain"!) is done after doing the etag precondition check insetad of before.
> Some cleanups that came out of the temp view experiment

- common-pg/src/main/scala/com/socrata/pg/analyzer2/Rep.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/ResultExtractor.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRep.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
Postgresql's JDBC driver will read rows in fixed-size blocks; by default, it reads _all_ the results into memory before returning them.  You can make it stream by setting the fetch size (in rows), so we'll do that.
Specifically, we'll set the fetch size based on the types of columns in the result - in particular geo types routinely use a lot of memory, so we'll consider such types as being "large" and set a small fetch size when one exists in the result.
> Stream results from the database

- common-pg/src/main/scala/com/socrata/pg/analyzer2/ProvenanceTracker.scala
Unlike the other place we do this (construct and fill an array provenances corresponding the the provenances of the various output columns of a query) here we're modifying it on each loop rather than merely setting it, so it has to be pre-filled with empty sets.
> Fix a nullpointerexception

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SqlizeAnnotation.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/Sqlizer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
...and when doing a pretty-print, add it as a comment just as is done when columns are referenced.
> Annotate the outputs of SELECTs with their human name

- common-pg/src/main/scala/com/socrata/pg/analyzer2/RewriteSearch.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLRewriteSearch.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/TestRewriteSearch.scala
* The query conversion function is actually plainto_tsquery, not to_tsquery
* the first argument to to_tsvector and plainto_tsquery is _not_ a text literal, though it looks like one.
> Search fixes

- common-pg/src/main/scala/com/socrata/pg/analyzer2/Sqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SqlizerTest.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
* Make it possible to _not_ apply wrapper functions to top-level output columns (e.g., the "convert to wkb" call that gets done on geometries)
* Remove the availableSchemas parameter from the API.  It's part of the sqlizer's internal state tracking and was always just an empty map.
> More flexible sqlization and a slightly cleaner API

- Jenkinsfile
- soql-server-pg/build.sbt
- store-pg/build.sbt
* The filenames no longer contain the version number
* The files are stored in target instead of target/scala-$version
> Simplify assembly filenames

- Jenkinsfile
For soql-server-pg and secondary-watcher-pg:
- We use the sbt version incremented using sbt release for git tags for releases.
- For deploy tags, we use the format `${env.SERVICE_VERSION}_${env.BUILD_ID}_${env.SERVICE_SHA}`.  This is for release builds as well as staging builds.
For soql-server-pg and secondary-watcher-pg:
- We use the release name for both the git tag and deploy tag for releases.  
- For staging builds, we use the existing format with `SERVICE_VERSION = 'STAGING'`.
> EN-61797: use release name as git tag and deploy tag

- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
Instead of decompressing them and then re-compressing them at query-coordinator and soda-fountain, just compress them once here and then pass that through.  This means no more transparent gzip compression from jetty, so disable that for the (new) content-type that this response has.
> On the new query path, do less de/recompression of responses

- common-pg/src/main/scala/com/socrata/pg/analyzer2/TransformManager.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/rollup/RollupInfo.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/rollup/RollupRewriter.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/rollup/RollupExactTest.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/rollup/RollupRewriterTest.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/rollup/RollupTestHelper.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
..also actually implement `tableExists`
> Track rollup IDs through rollup-rewriting and metricize the chosen ones

- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTestRedshift.scala
made sure that implementations for the following conditional functions are also valid in redshift:
- case
- iif
- coalesce
- nullif
> EN-63009 - Dalia/conditional functions

- common-pg/src/main/resources/com/socrata/pg/store/schema/20231011-create-extension-unaccent.xml
- common-pg/src/main/scala/com/socrata/pg/soql/SqlFunctions.scala
- project/Dependencies.scala
This maps the SOQL `unaccent` function to its Postgres equivalent (see https://github.com/socrata-platform/soql-reference/pull/349).
Because the function belongs to a trusted extension ([reference](https://www.postgresql.org/docs/current/unaccent.html)), this also includes a migration to create the extension.
> Add unaccent extension and SOQL function

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerRedshift.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTestRedshift.scala
all geo cast functions are implemented through st_geomfromtext since redshift doesn’t have more specific functions for the different geom subtypes. there is no guarantee that the subtype casted is the actual subtype of the geom data.
implementing the function TextToLocation is blocked by the ticket https://socrata.atlassian.net/browse/EN-62999.
> [EN-63003] - Dalia/geo casts

- common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerBasicTest.scala
This also attempts to fix a related bug whereby compound columns would produce single-column null literals, but for some reason it does not? This definitely produces a multi-column ParametricSql when appropriate, but sqlization of `select null::url` still produces `SELECT (null :: TEXT)` and then tries to read two columns out of the result.  I'm not sure why!
> Type-annotate NULL literals in old-analyzer SQL generation

- common-pg/src/main/scala/com/socrata/pg/soql/SoQLAnalysisSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
- soql-server-pg/src/test/scala/com/socrata/pg/server/SoQLUnionTest.scala
Sometimes `select blah OP select bleh` is fine, but sometimes it absolutely needs to be `(select blah) OP...` (e.g., if it has a LIMIT. Since it's never _wrong_ to fully-parenthesize, just always do that.
> EN-47308: Always fully-parenthesize select merge operations

- common-pg/src/main/scala/com/socrata/pg/analyzer2/metatypes/CopyCache.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/metatypes/InputMetaTypes.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/metatypes/RollupMetaTypes.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/ordering/package.scala
- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ETagify.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
Idly thinking about how to provide the functionality provided by the x-soda2-data-out-of-date header without unconditionally involving truth on the read path, and plumbing this information out would definitely be part of any such thing.
> Return the data-versions of all referenced datasets in the cjson header

- common-pg/src/main/scala/com/socrata/pg/store/SoQLCommon.scala
- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
Because they're gone from the DC library (but the DC's rep-selector function is still there so that continues to be used)
> Update the old-analyzer query path to use the new cjson reps too

- project/Dependencies.scala
- soql-server-pg/build.sbt
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ResultCache.scala
In particular, "count(*)" is a common request to make which can be very expensive to compute but which will result in A Number.  Let's avoid computing that over and over as much as possible!
> Cache known-to-be-small responses in memory

- Jenkinsfile
This commit moves the release tagging after a successful docker build.  In order to do this, it separates the docker build from the publishing of the images into separate Jenkinsfile steps.
> EN-65713: separate docker build from publish

- common-pg/src/main/scala/com/socrata/pg/analyzer2/metatypes/RollupMetaTypes.scala
- common-pg/src/main/scala/com/socrata/pg/query/QueryServerHelper.scala
- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- common-pg/src/main/scala/com/socrata/pg/store/SecondaryManagerBase.scala
- project/Dependencies.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
- store-pg/src/main/scala/com/socrata/pg/store/events/RollupCreatedOrUpdatedHandler.scala
- store-pg/src/test/scala/com/socrata/pg/store/RollupTest.scala
Just temporarily until we update exsting new-analyzer rollups, then all rollups will use resource names and the TableName class can be removed.
> EN-66368: v3 rollups use either internal names or resource names

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLExtraContext.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
* Only use for etag generation those parts of the context which are actually used.  If a non-literal is used, then and only then assume "all of it" when generating the fingerprint.
* make it so that the very fact of getting `now` out of the extra-context records the fact that `now` was used
The first one means that queries which do not actually use the system context will not return different fingerprints for different users.
> Improve cachability on domains with user context turned on

- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ObfuscatorHelper.scala
Using plpgsql here was overkill; A SQL function can be inlined by the query planner and this is a trivial function.
> Improve id/version sqlization

- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
They're _discarded_ so we don't care about them anymore.
> Don't attempt to take locks on rollups for discarded copies

- project/Dependencies.scala
- store-pg/src/main/scala/com/socrata/pg/store/PGSecondary.scala
Significant perf win on datasets with lots of copies
> Don't grab all copies when we don't need all copies

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/DynamicSystemContextHelper.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
This was always a hack; PG's settings system was absolutely not meant for this and it's always bothered me that we were using it even beyond the bug that if you happened to use an unset config val in a session where it had been previously set, you'd get back an empty string insetad of null.
Now instead if dynamic config vals are used in a query, we create a function in pg_temp (which is specifically for storing per-transaction stuff) and call it there.
> Don't use pg config for dynamic system context lookups

- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
Shouldn't actually do anything right now, but it keeps us robust in the face of configuration changes - now both sides of this read explicitly expect to be using UTF-8, instead of one side being implicit.
> Add an ENCODING parameter to the COPY command used for querying

- common-pg/src/main/scala/com/socrata/pg/query/QueryServerHelper.scala
- common-pg/src/main/scala/com/socrata/pg/soql/ExprSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/soql/Sqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/store/IndexManager.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerJoinTest.scala
- common-pg/src/test/scala/com/socrata/pg/soql/SqlizerTest.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
PG column names can be of any length, but only the first 63 characters are significant.  This is a problem if two SoQL aliases exist which are longer than that.  So, we'll remap such columns at sql-generation time to i#### (where #### is just an incrementing counter as they're encountered).
This is tricker than it sounds, because it's entirely possible for a user-specified column to be called "i####" and we don't want to collide. So for those columns, we'll remap even if the name is below the pg length limits.
Why aren't we just remapping everything?  Because we have no visibility into which columns are physical database columns (and so must not be renamed) and which columns are intermediate (and so can be).  Also there's a massive pile of tests that assume column names don't ordinarily …
> EN-69912: Prevent the old-analyzer from generating bad aliases

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLExtraContext.scala
In the OA path it truncates to seconds, so do the same.
Also add `withZone(DateTimeZone.UTC)` to make sure everything agrees about the zone computations should be done in by default.
> Make new-analyzer agree with old-analyzer wrt get_utc_date precision

- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLExprSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLExtraContext.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/SoQLSqlizer.scala
- common-pg/src/main/scala/com/socrata/pg/analyzer2/TimestampProvider.scala
- common-pg/src/main/scala/com/socrata/pg/store/RollupManager.scala
- common-pg/src/test/scala/com/socrata/pg/analyzer2/SoQLFunctionSqlizerTest.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ETagify.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/analyzer2/ProcessQuery.scala
Before:
* calling `get_utc_date` would make your query's `Last-Modified` and `ETag` headers change every second
Now:
* `Last-Modified` still changes every second, but the `ETag` (and hence also the automatic response cache) will take into account certain "coarsening" function calls surrounding the `get_utc_date` call.  In particular, if you _immediately_ convert the result of `get_utc_date` into a `floating_timestamp` in some literal time zone and then use any of the `date_extract_...` functions or any of the field accessors that return values at day-resolution or coarser, the etag will be computed with that coarsened value instead.
> Make it possible to cache coarsended expressions of get_utc_date

- common-pg/src/main/rust/blowfish.rs
We don't want to convert these u64s "to big endian", because we're not operating on bytes.  We want to unconditionally swap the byte order.
> NO-JIRA: fix database-side :id and :version obfuscation on big-endian

- soql-server-pg/src/main/scala/com/socrata/pg/server/EnablingHandler.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServer.scala
- soql-server-pg/src/main/scala/com/socrata/pg/server/QueryServerBroker.scala
In an attempt to force requests to other instances rather than getting to the max queue size and then forcibly closing connections.
> EN-68022: Remove a pg instance's registration when it's full
